#!/usr/bin/env python3
"""Canonicalize only Simplex's unordered module declarations, not artifacts."""
import pathlib
import re
import sys

HEADER = '// This file is @generated by Simplex. Do not edit manually.\n\n#![allow(clippy::all)]\n'
MODULE = re.compile(r'#\[rustfmt::skip\]\npub mod ([a-zA-Z_][a-zA-Z_0-9]*);\n')


def canonicalize(source: str) -> str:
    if not source.startswith(HEADER):
        raise ValueError('unexpected generated module header')
    body = source[len(HEADER):]
    names = MODULE.findall(body)
    if not names or MODULE.sub('', body) or len(names) != len(set(names)):
        raise ValueError('unexpected or duplicate generated module declarations')
    return HEADER + ''.join(f'#[rustfmt::skip]\npub mod {name};\n' for name in sorted(names))


if __name__ == '__main__':
    path = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'src/artifacts/mod.rs')
    path.write_text(canonicalize(path.read_text()))
