[build]
src_dir = "."
simf_files = ["*.simf"]
out_dir = "../src/artifacts-v2"

[dependencies]
std = { path = "../deps/simplicityhl-std" }

[test]
mnemonic = "exist carry drive collect lend cereal occur much tiger just involve mean"
bitcoins = 10_000_000
